const Screens = {
    STARTUP: 'STARTUP',
    SIGNIN: 'SIGNIN',
    SIGNUP: 'SIGNUP',
    OTP: 'OTP',
    RESET_PASS: 'RESET_PASS',
    CREATE_PROFILE: 'CREATE_PROFILE',

    DEVICE_INSTALATION_LIST: 'DEVICE_INSTALATION_LIST',
    DEVICE_INSTALATION_REGISTER: 'DEVICE_INSTALATION_REGISTER',
    DEVICE_INSTALATION_PROGRESSING: 'DEVICE_INSTALATION_PROGRESSING',
    DEVICE_INSTALATION_LOADING: 'DEVICE_INSTALATION_LOADING',

    INTRUDOCTION: 'INTRUDOCTION',
    TABS: 'TABS',
    HOME: 'HOME',
    DASHBOARD: 'DASHBOARD',
    MAP: 'MAP',
    CREATE_DEVICE: 'CREATE_DEVICE',
    CREATE_UPDATE: 'CREATE_UPDATE',
    LOADING_DEVICE: 'LOADING_DEVICE',
    MENU: 'MENU',
    REMOTE1: 'REMOTE1',
    REPORT_ROUTING: 'REPORT_ROUTING'
}
export default Screens